//
// Created by Loïc Colat on 22/01/2020.
//

#ifndef MULTI_THREAD_PICTURE_CONVERTER_COMMAND_LINE_CHECK_H
#define MULTI_THREAD_PICTURE_CONVERTER_COMMAND_LINE_CHECK_H
#include <dirent.h>
#endif //MULTI_THREAD_PICTURE_CONVERTER_COMMAND_LINE_CHECK_H
